backend: # Set up your backend
  name: github
  repo: Shrey-Viradiya/shrey-viradiya.github.io
  branch: master
  site_domain: vigilant-chandrasekhar-01f1c0.netlify.com

local_backend: true # Optional if you want to use the local proxy mode

publish_mode: editorial_workflow
media_folder: media    # I'm not using these default media directories at the moment.
public_folder: /media

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    delete: true
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "images"
    public_folder: "./images"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", valueField: "name", searchFields: ["name"] }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Hero", name: "hero", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "authors"
    label: "Authors"
    folder: "content/authors/authors"
    create: true
    delete: true
    format: "yml"
    identifier_field: "name"
    media_folder: "avatars"
    public_folder: "./avatars"
    editor:
      preview: false
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Bio, name: bio, widget: string }
      - { label: Featured, name: featured, widget: boolean, default: false }
      - { label: Avatar, name: avatar, widget: image }
      - { label: Social, name: social, widget: list, collapsed: false, field: { label: URL, name: url, widget: string } }
      - label: Education
        name: education
        widget: list
        collapsed: false
        fields: 
          - {label: Institution, name: institution, widget: string}
          - {label: Stream, name: stream, widget: string}
          - {label: Year, name: year, widget: string, pattern: ['(19|20)\d{2}-(19|20)\d{2}$', "Should be in YYYY-YYYY format"] }
          - {label: Score, name: score, widget: number, value_type: float}